# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iosBLE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  pod 'Alamofire', '~> 4.4'

  # Pods for iosBLE

end
